/* ----------------------------------------------------------------------------
 * MATH.DLL - Math extenstions for DIV Games Studio.
 * (C) VisualStudioEX3, José Miguel Sánchez Fernández - 2020
 * DIV Games Studio 2 (C) Hammer Technologies - 1998, 1999
 * ---------------------------------------------------------------------------- */
 
#ifndef __MATH_H_
#define __MATH_H_

#include "..\common.h"

void min();
void max();
void clamp();
void isClamped();

#endif